### ISSUE TITLE
Coap plugin started, but can't use it

### ISSUE THREAD

**Issue by JsonMa** [emqtt/emq-coap#78]
## Environment
emq 2.3.9 in docker, official image from [here](http://www.emqtt.com/downloads/2316/docker)

## Expected behaviour
I can start the coap plugin from the dashboard and connect to it with clients [libcoap](https://github.com/obgm/libcoap) or [coap-cli](https://github.com/mcollina/coap-cli)

### Started image with:

`sudo docker run -tid --name emqtt-coap -p 5683:5683 -p 5684:5684 -p 1883:1883 -p 8083:8083 -p 8883:8883 -p 8084:8084 -p 18083:18083 emqttd-docker-v2.3.9`
### Open plugin with

1. `sudo docker container exec -it [containerID] /bin/sh`
2. `./bin/emqttd_ctl plugins load emq_coap`
### Result

1. Dashboard shows up
![image](https://user-images.githubusercontent.com/13042493/42084634-caa2a260-7bc0-11e8-8218-e0e941478c80.png)
2. Port listen
![image](https://user-images.githubusercontent.com/13042493/42084690-fa07ac12-7bc0-11e8-8456-ffc72c649ec2.png)
3. Logs
![image](https://user-images.githubusercontent.com/13042493/42084811-508a6318-7bc1-11e8-8ba7-90a5c1071336.png)

### Connetct through libcoap
![image](https://user-images.githubusercontent.com/13042493/42084893-8d658e84-7bc1-11e8-9752-b0cf39afcdc6.png)

**Comment by terry-xiaoyu** [comment]
I belive the port 5683 should be UDP, not TCP.

**Comment by JsonMa** [comment]
Thanks, i have resolved this problem by changing tcp port to udp
